# name: MY-Portfolio-Website

# on:     ##Branch you need to push changes
#   push:
#     branches:
#     - main

# jobs:      
#   build-and-deploy:
#     runs-on: ubuntu-latest  
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v1 #Script actions

#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1

#     - name: Deploy static site to S3 bucket
#       run: aws s3 sync . s3://my-portfolio-website-2023 --delete 
